# Generated by Django 4.2.5 on 2024-06-22 16:14

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_url',
            field=models.ImageField(blank=True, null=True),# upload_to=app.models.Post.upload_to),
        ),
        migrations.AddField(
            model_name='user',
            name='image_url',
            field=models.ImageField(blank=True, null=True),# upload_to=app.models.User.upload_to),
        ),
    ]
