# Generated by Django 4.2.5 on 2024-06-22 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_post_image_url_remove_user_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
