# Generated by Django 4.2.5 on 2024-06-24 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_post_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_hash',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
